@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpwX2ZhcmlhQGlkLnVmZi5iciIsImlhdCI6MTY3OTEwNDMyNSwiZXhwIjoxNjc5MTA3OTI1LCJzdWIiOiIxIn0.gH60hUYnTUPH7_oRC200z6I3KB52EUqPl2ExpFULAO0
### LOGIN
POST http://localhost:3000/login
content-type: application/json

{
  "email": "jp_faria@id.uff.br",
  "password":"pucminas"
}


### GASTOS
GET http://localhost:3000/660/gastos
Authorization: Bearer {{TOKEN}}

### CREATE
POST http://localhost:3000/660/gastos
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
  "tipo": 0,
  "data": "15/01/2022",
  "preco": 7.77,
  "valor": 150.00,
  "odometro": 35000
}

### UPDATE
PUT http://localhost:3000/660/gastos/4
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
  "tipo": 1,
  "data": "10/01/2023",
  "preco": 7.5,
  "valor": 130.00,
  "odometro": 34000
}


### GET GASTO
GET http://localhost:3000/660/gastos/5
Authorization: Bearer {{TOKEN}}

### DELETE GASTO
DELETE http://localhost:3000/660/gastos/3
Authorization: Bearer {{TOKEN}}